#ifndef __INCLUDED_SETTING_LINUX_BOOT_H__
#define __INCLUDED_SETTING_LINUX_BOOT_H__

#define LINUX_VGICD_ADDR 0xbe004000
#define LINUX_START_ADDR 0x80008000
#define LINUX_MEMORY_AREAS MemArea
#define LINUX_MEMORY_AREA_NUM MemAreaNum
#define LINUX_DBT_ADDR 0x8ef1c000

#endif
